accounts/urls.py
from django.conf.urls import url
from .views import *

app_name = 'accounts'

urlpatterns = [

    url(r'^login/$', login_view, name="login"),
    url(r'^register/$', register_view, name="register"),
    url(r'^logout/$', logout_view, name="logout"),
]

blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from home.views import home_view, api
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [

    url(r'^$', home_view, name='home'),

    url(r'^api/', api, name='api'),

    url(r'^post/', include('post.urls')),

    url(r'^accounts/', include('accounts.urls')),

    url(r'^admin/', admin.site.urls),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.conf.urls import url
from .views import *

app_name = 'post'

urlpatterns = [

    url(r'^index/$', post_index, name="index"),

    url(r'^create/$', post_create, name='create'),

    url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),

    url(r'^(?P<slug>[\w-]+)/update/$', post_update, name="update"),

    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete, name='delete'),
]

home/views.py
from django.shortcuts import render
from django.core.files.storage import FileSystemStorage
import time, os

def home_view(request):

    if request.user.is_authenticated:
        context = {
            'isim': 'Serhat',
            'soyisim': 'Arslan'
        }
    else:
        context = {
            'isim': 'Misafir',
            'soyisim': 'Kullanıcı'
        }

    if request.method == 'POST':
        import main

        myfile = request.FILES['myfile']
        fs = FileSystemStorage()
        filename = fs.save(myfile.name, myfile)
        uploaded_file_url = fs.url(filename)

        start_time = time.time()
        main.run()
        end_time = time.time() - start_time
        print(round(end_time, 2))

        dir_path = os.path.abspath('../..')

        no_face = dir_path + '/static/no_face'
        has_face = dir_path + '/static/has_face'

        content = {
            'noface': os.listdir(no_face),
            'hasface': os.listdir(has_face),
            'noface_zip': '/media/result/noface.zip',
            'hasface_zip': '/media/result/hasface.zip',
        }

        return render(request, 'result.html', content)

    return render(request, 'home.html', context)


def index(request):

    if request.POST:
        print('çalış bebeğim')
        import delete

        delete.delete_items()

    return render(request,'result.html')

def api(request):
    import main

    myfile = request.GET.get('url', 'Not Found')


    result = main.api_url(myfile)

    print(result)


    return render(request, 'home.html')

templates/base.html
{% load static %}
<html>
<html lang="tr">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, inital-scale=1">
    <title>{% block title %} Pytest Project {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>

    {% include 'message.html' %}

    {% include 'header.html' %}


    {% block body %}

    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="{% static 'js/slider.js' %}"></script>
    <!--<script src="{% static 'js/bootstrap.min.js' %}"></script>-->
</body>
</html>

templates/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="{% url 'home' %}">PyTest</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        {% if request.user.is_authenticated %}
          <a class="nav-link" href="{% url 'post:create' %}">Yazı Ekle! <span class="sr-only">(current)</span></a>
        {% endif %}
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'post:index' %}">Blog</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Hakkında</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">İletişim</a>
      </li>
      {% if not request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:register' %}">Üye ol!</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:login' %}">Giriş Yap</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:logout' %}">Çıkış</a>
        </li>
      {% endif %}

    </ul>
    <form class="form-inline my-2 my-lg-0" role="search" method="GET" >
      <input class="form-control mr-sm-2" type="search" name="q" placeholder="Search" aria-label="Search" value="{{ request.GET.q }}">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

templates/home.html
{% extends 'base.html' %}
{% block title %} Anasayfa {% endblock %}

{% block body %}

   <div class="container-fluid">
      <div class="row">
         <div class="col-md-6 offset-3">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <br><br><br><br>
                <h1>Welcome to image recognition!</h1>
                <br><br><br><br>
                <input type="file" name="myfile">
                <button class="btn-primary" type="submit" value="Gönder">Run Script!</button>
            </form>
        </div>
      </div>
   </div>

{% endblock %}

templates/message.html
{% if messages %}
        {% for message in messages %}
        <div class="alert alert-success alert-dismissible" role="alert">
          <div>{{ message }}</div>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
{% endif %}

templates/result.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Pytest {% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        {% if noface %}
        <div class="col-md-6">
            <h2>No Face</h2>
            <div class="slider">
                {% for no_items in noface %}
                    <img src="/static/no_face/{{no_items}}" alt="">
                {% endfor %}
            </div>
             <a href="{{noface_zip}}" download>
                 <button class="btn-primary" type="submit">Download!</button>
             </a>
        </div>
        {% endif %}
        {% if hasface %}
        <div class="col-md-6">
            <h2>Has Face</h2>
            <div class="slider">
                {% for has_items in hasface %}
                    <img src="static/has_face/{{has_items}}" alt="">
                {% endfor %}
            </div>
            <a href="{{hasface_zip}}" download>
                 <button class="btn-primary" type="submit">Download!</button>
             </a>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}